CREATE TABLE IF NOT EXISTS CUSTOMERS
(ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
ADDRESS VARCHAR(1000) NOT NULL,
BUDGET DECIMAL NOT NULL);
